#!/usr/bin/env bash
# Script to change localhost and facebook.com IP resolution

cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
